version: '3.8'

services:
  postgres1:
    image: postgres:15
    container_name: postgres1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: server1_db
    ports:
      - "5432:5432"
    volumes:
      - postgres1_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network  # Tarmoqqa ulash

  app:
    build: .
    container_name: go_app
    depends_on:
      - postgres1
    ports:
      - "8082:8082"
    environment:
      DATABASE_URL: "host=postgres1 port=5432 user=postgres password=1111 dbname=server1_db sslmode=disable"
    networks:
      - app_network

volumes:
  postgres1_data:

networks:
  app_network:
    driver: bridge
